name: Deploy Image to ACR and AKS

on:
  push:
    branches:
      - master

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Deploy # 1 to Azure Container Registry
#

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

#Login to dockerhub.io. Other repos also work fine
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrgithubactions.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Build and Push container image
    - run: |
        docker build . -t acrgithubactions.azurecr.io/angularawebapp:latest
        docker push acrgithubactions.azurecr.io/angularawebapp:latest

        # Deploy the Docker image to the IKS cluster
    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group IaCAKS_Zone --name AKSCluterMX01
        kubectl apply -f deployment-service.yaml
        kubectl get services -o wide